# roles/elastic_agent_uninstall_role/tasks/uninstall.yml
---
- name: Check if Elastic Agent service is running
  command: systemctl is-active --quiet elastic-agent
  register: elastic_agent_service_status
  failed_when: false
  changed_when: false

- name: Check if Elastic Agent is installed
  stat:
    path: "{{ elastic_agent_install_dir }}"
  register: elastic_agent_installed

- name: Check if Elastic Agent symlink exists
  stat:
    path: /usr/bin/elastic-agent
  register: elastic_agent_symlink

- name: Elastic Agent is not installed, skipping uninstallation
  debug:
    msg: "Elastic Agent is not installed. Skipping uninstallation."
  when: elastic_agent_service_status.rc != 0 and not elastic_agent_installed.stat.exists and not elastic_agent_symlink.stat.exists

- name: Stop and disable Elastic Agent service
  systemd:
    name: elastic-agent
    state: stopped
    enabled: no
  when: elastic_agent_service_status.rc == 0 or elastic_agent_installed.stat.exists or elastic_agent_symlink.stat.exists

- name: Unenroll Elastic Agent from Fleet Server
  shell: >
    /usr/bin/elastic-agent uninstall --force
  register: uninstall_output
  failed_when: false
  when: elastic_agent_symlink.stat.exists

- name: Display uninstall output
  debug:
    msg: "{{ uninstall_output.stderr }}"
  when: elastic_agent_symlink.stat.exists

- name: Retrieve Elastic Agent logs
  shell: >
    journalctl -u elastic-agent --no-pager
  register: elastic_agent_logs
  when: elastic_agent_symlink.stat.exists

- name: Display Elastic Agent logs
  debug:
    msg: "{{ elastic_agent_logs.stdout }}"
  when: elastic_agent_symlink.stat.exists

- name: Remove Elastic Agent files
  file:
    path: "{{ elastic_agent_install_dir }}"
    state: absent
  when: elastic_agent_symlink.stat.exists

- name: Remove Elastic Agent symlink
  file:
    path: /usr/bin/elastic-agent
    state: absent
  when: elastic_agent_symlink.stat.exists

- name: Remove Elastic Agent configuration directory
  file:
    path: /etc/elastic-agent
    state: absent
  when: elastic_agent_symlink.stat.exists

- name: Remove Elastic Agent log directory
  file:
    path: /var/log/elastic-agent
    state: absent
  when: elastic_agent_symlink.stat.exists

- name: Display Elastic Agent uninstallation status
  debug:
    msg: "Elastic Agent has been successfully uninstalled and unenrolled from the Fleet Server."
  when: elastic_agent_symlink.stat.exists
