# elastic_agent_role/tasks/status.yml
---
- name: Check Elastic Agent service status
  systemd:
    name: elastic-agent
    state: started
    enabled: yes
  when: elastic_agent_installed.stat.exists or elastic_agent_new_install is defined

- name: Output Elastic Agent service status
  command: systemctl status elastic-agent
  register: elastic_agent_status
  when: elastic_agent_installed.stat.exists or elastic_agent_new_install is defined

- name: Display Elastic Agent service status
  debug:
    msg: "{{ elastic_agent_status.stdout }}"
  when: elastic_agent_installed.stat.exists or elastic_agent_new_install is defined

- name: Get Elastic Agent enrollment status
  shell: /opt/elastic-agent-8.11.4-linux-x86_64/elastic-agent status
  register: elastic_agent_enrollment_status
  when: elastic_agent_installed.stat.exists or elastic_agent_new_install is defined

- name: Display Elastic Agent enrollment status
  debug:
    msg: "Elastic Agent enrollment status: {{ elastic_agent_enrollment_status.stdout }}"
  when: elastic_agent_installed.stat.exists or elastic_agent_new_install is defined

- name: Fail if Elastic Agent service is not running
  fail:
    msg: "Elastic Agent service is not running!"
  when: elastic_agent_status is defined and elastic_agent_status.stdout.find('active (running)') == -1

- name: Fail if Elastic Agent is not enrolled
  fail:
    msg: "Elastic Agent is not properly enrolled with the Fleet Server!"
  when: elastic_agent_enrollment_status is defined and
        ("(HEALTHY) Connected" not in elastic_agent_enrollment_status.stdout or
         "(HEALTHY) Running" not in elastic_agent_enrollment_status.stdout)

- name: Output Elastic Agent log file location
  command: |
    find /var/log -type f -name 'elastic-agent*'
  register: elastic_agent_logs
  when: elastic_agent_installed.stat.exists or elastic_agent_new_install is defined

- name: Display Elastic Agent log file location
  debug:
    msg: "Elastic Agent log files: {{ elastic_agent_logs.stdout_lines }}"
  when: elastic_agent_installed.stat.exists or elastic_agent_new_install is defined
